# Generated by Django 4.0.6 on 2023-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradd',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('C', 'Customer'), ('A', 'Admin')], default='C', max_length=50, verbose_name='user type'),
        ),
    ]
