# Generated by Django 4.0.4 on 2022-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.FileField(upload_to='menu/'),
        ),
    ]
