# Generated by Django 4.0.4 on 2022-05-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_product_picture_ext_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
