# Generated by Django 4.0.4 on 2022-06-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
