# Generated by Django 4.0.4 on 2022-06-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
